In [1]:
from poly_graphs_lib.utils import PROJECT_DIR
import os
import json
import numpy as np
from glob import glob 

import pymatgen.core as pmat

from poly_graphs_lib.database.json import DB_DIR

database_files=glob(DB_DIR + '\*.json')


In [2]:
database_files=glob(DB_DIR + '\*.json')

In [3]:
success_files=[]
failed_files=[]
for file in database_files:
    with open(file, 'r') as f:
        data = json.load(f)

        if data["coordination_environments_multi_weight"] is not None:
            success_files.append(file)
        else:
            failed_files.append(file)

print("Success: ", len(success_files))
print("Failed: ", len(failed_files))

print("Success: ", success_files[:10])
print("Failed: ", failed_files[:10])

Success:  8179
Failed:  2468
Success:  ['Z:\\Research Projects\\crystal_generation_project\\Graph_Network_Project\\data\\processed\\materials_project_nelements_2\\json_database\\mp-1000.json', 'Z:\\Research Projects\\crystal_generation_project\\Graph_Network_Project\\data\\processed\\materials_project_nelements_2\\json_database\\mp-10000.json', 'Z:\\Research Projects\\crystal_generation_project\\Graph_Network_Project\\data\\processed\\materials_project_nelements_2\\json_database\\mp-10004.json', 'Z:\\Research Projects\\crystal_generation_project\\Graph_Network_Project\\data\\processed\\materials_project_nelements_2\\json_database\\mp-10009.json', 'Z:\\Research Projects\\crystal_generation_project\\Graph_Network_Project\\data\\processed\\materials_project_nelements_2\\json_database\\mp-1001.json', 'Z:\\Research Projects\\crystal_generation_project\\Graph_Network_Project\\data\\processed\\materials_project_nelements_2\\json_database\\mp-10014.json', 'Z:\\Research Projects\\crystal_genera

In [104]:
from pymatgen.analysis.chemenv.coordination_environments.chemenv_strategies import SimplestChemenvStrategy,MultiWeightsChemenvStrategy
from pymatgen.analysis.chemenv.coordination_environments.coordination_geometry_finder import LocalGeometryFinder
from pymatgen.analysis.chemenv.coordination_environments.structure_environments import LightStructureEnvironments
import copy

file=failed_files[1]
with open(file) as f:
    db = json.load(f)
    struct = pmat.Structure.from_dict(db['structure'])


print(struct.atomic_numbers)
print(struct.cart_coords)
lgf = LocalGeometryFinder()
lgf.setup_structure(structure=struct)


se = lgf.compute_structure_environments(maximum_distance_factor=1.41,
                                        minimum_angle_factor=0.05,
                                        voronoi_normalized_distance_tolerance=0.05,
                                        voronoi_normalized_angle_tolerance=0.03,
                                        only_cations=False)
strategy = SimplestChemenvStrategy(distance_cutoff=1.41, angle_cutoff=0.3)
# se = lgf.compute_structure_environments(maximum_distance_factor=2.5,only_cations=False)
# strategy =SimpleAbundanceChemenvStrategy()
# strategy = MultiWeightsChemenvStrategy.stats_article_weights_parameters()
lse = LightStructureEnvironments.from_structure_environments(strategy=strategy, structure_environments=se)



coordination_environments = copy.copy(lse.coordination_environments)
for i,env in enumerate(lse.coordination_environments):
    if env is None:
        print(env)
        coordination_environments[i]=[{'ce_symbol': 'S:1', 'ce_fraction': 1.0, 'csm': 0.0, 'permutation': [0]}]
        # env=[{'ce_symbol': 'UKNOWN:1', 'ce_fraction': 0.999999999677424, 'csm': 0.0, 'permutation': []}]

print(coordination_environments)

(72, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5)
[[0.    0.    0.   ]
 [4.541 2.128 6.096]
 [3.009 2.128 6.981]
 [4.031 0.683 5.211]
 [3.52  3.573 4.327]
 [2.498 0.683 6.096]
 [3.52  3.573 6.096]
 [4.541 2.128 4.327]
 [1.987 3.573 5.211]
 [2.498 0.683 4.327]
 [1.476 2.128 6.096]
 [3.009 2.128 3.442]
 [1.476 2.128 4.327]]
None
[[{'ce_symbol': 'S:1', 'ce_fraction': 1.0, 'csm': 0.0, 'permutation': [0]}], [{'ce_symbol': 'T:5', 'ce_fraction': 1, 'csm': 8.895136906239435, 'permutation': [0, 2, 4, 1, 3]}], [{'ce_symbol': 'T:5', 'ce_fraction': 1, 'csm': 8.895136700766718, 'permutation': [0, 2, 4, 1, 3]}], [{'ce_symbol': 'T:5', 'ce_fraction': 1, 'csm': 8.895137212283021, 'permutation': [1, 2, 4, 0, 3]}], [{'ce_symbol': 'T:5', 'ce_fraction': 1, 'csm': 8.895135488445234, 'permutation': [0, 3, 4, 1, 2]}], [{'ce_symbol': 'T:5', 'ce_fraction': 1, 'csm': 8.895135488445232, 'permutation': [1, 3, 4, 0, 2]}], [{'ce_symbol': 'T:5', 'ce_fraction': 1, 'csm': 8.895140290477322, 'permutation': [0, 2, 4, 1, 3]}], [{'

In [98]:

for file in failed_files:
    with open(file) as f:
        db = json.load(f)
        struct = pmat.Structure.from_dict(db['structure'])


    # print(struct.atomic_numbers)
    # print(struct.cart_coords)
    lgf = LocalGeometryFinder()
    lgf.setup_structure(structure=struct)


    se = lgf.compute_structure_environments(maximum_distance_factor=1.41,
                                            minimum_angle_factor=0.05,
                                            voronoi_normalized_distance_tolerance=0.05,
                                            voronoi_normalized_angle_tolerance=0.03,
                                            only_cations=False)
    # strategy = SimplestChemenvStrategy(distance_cutoff=1.41, angle_cutoff=0.3)
    # # se = lgf.compute_structure_environments(maximum_distance_factor=2.5,only_cations=False)
    # # strategy =SimpleAbundanceChemenvStrategy()
    strategy = MultiWeightsChemenvStrategy.stats_article_weights_parameters()
    lse = LightStructureEnvironments.from_structure_environments(strategy=strategy, structure_environments=se)

    
    coordination_environments = lse.coordination_environments
    for env in coordination_environments:
        print(env)

0.0
0.99995446689259
0.99995446689259
0.9999544696022286
0.99995446689259
0.99995446689259
0.9999544696022286
[]
[{'ce_symbol': 'TL:3', 'ce_fraction': 0.999999999677424, 'csm': 8.761464129780458e-05, 'permutation': [0, 1, 2]}, {'ce_symbol': 'TY:3', 'ce_fraction': 3.22575885744014e-10, 'csm': 3.0303869270907966, 'permutation': [0, 1, 2]}]
[{'ce_symbol': 'TL:3', 'ce_fraction': 0.999999999677424, 'csm': 8.761464129780458e-05, 'permutation': [0, 1, 2]}, {'ce_symbol': 'TY:3', 'ce_fraction': 3.22575885744014e-10, 'csm': 3.0303869270907966, 'permutation': [0, 1, 2]}]
[{'ce_symbol': 'TL:3', 'ce_fraction': 0.9999999996774624, 'csm': 8.760942725292563e-05, 'permutation': [0, 1, 2]}, {'ce_symbol': 'TY:3', 'ce_fraction': 3.225374944981773e-10, 'csm': 3.03038692203472, 'permutation': [0, 1, 2]}]
[{'ce_symbol': 'TL:3', 'ce_fraction': 0.999999999677424, 'csm': 8.761464129778338e-05, 'permutation': [0, 1, 2]}, {'ce_symbol': 'TY:3', 'ce_fraction': 3.2257588574385784e-10, 'csm': 3.030386927090797, 'perm

KeyboardInterrupt: 