In [1]:
import os
import shutil

import numpy as np
from coxeter.families import PlatonicFamily

from poly_graphs_lib.poly_dataset import PolyhedraDataset
from poly_graphs_lib.poly_featurizer import PolyFeaturizer
from poly_graphs_lib import encoder, utils

In [2]:
project_dir = os.path.dirname(os.getcwd())
project_dir

'c:\\Users\\lllang\\Desktop\\Romero Group Research\\Research Projects\\crystal_generation_project\\Graph_Network_Project'

In [3]:
verts_tetra = PlatonicFamily.get_shape("Tetrahedron").vertices - np.mean(PlatonicFamily.get_shape("Tetrahedron").vertices, axis = 0)
verts_cube = PlatonicFamily.get_shape("Cube").vertices
verts_oct = PlatonicFamily.get_shape("Octahedron").vertices
verts_dod = PlatonicFamily.get_shape("Dodecahedron").vertices
verts_tetra_rot = (verts_tetra).dot(utils.rot_z(theta=25))
poly_list = [verts_tetra,verts_cube,verts_oct,verts_dod,verts_tetra_rot]

In [4]:
obj = PolyFeaturizer(vertices=verts_cube)

In [5]:
encoder.face_sides_bin_encoder(obj.face_sides)

array([[0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.]])

In [6]:
obj.face_areas

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [7]:
encoder.gaussian_continuous_bin_encoder(obj.face_areas,min_val=0, max_val=40, sigma= 2)

array([[7.78800783e-001, 7.78800783e-001, 1.05399225e-001,
        1.93045414e-003, 4.78511739e-006, 1.60522806e-009,
        7.28772410e-014, 4.47773244e-019, 3.72336312e-025,
        4.19009319e-032, 6.38150345e-040, 1.31532589e-048,
        3.66905962e-058, 1.38511937e-068, 7.07669818e-080,
        4.89311226e-092, 4.57878997e-105, 5.79865542e-119,
        9.93836441e-134, 2.30522632e-149, 7.23641152e-166],
       [7.78800783e-001, 7.78800783e-001, 1.05399225e-001,
        1.93045414e-003, 4.78511739e-006, 1.60522806e-009,
        7.28772410e-014, 4.47773244e-019, 3.72336312e-025,
        4.19009319e-032, 6.38150345e-040, 1.31532589e-048,
        3.66905962e-058, 1.38511937e-068, 7.07669818e-080,
        4.89311226e-092, 4.57878997e-105, 5.79865542e-119,
        9.93836441e-134, 2.30522632e-149, 7.23641152e-166],
       [7.78800783e-001, 7.78800783e-001, 1.05399225e-001,
        1.93045414e-003, 4.78511739e-006, 1.60522806e-009,
        7.28772410e-014, 4.47773244e-019, 3.72336312e-

In [8]:
face_sides_features = encoder.face_sides_bin_encoder(obj.face_sides)
face_areas_features = obj.face_areas

node_features = np.concatenate([face_areas_features,face_sides_features,],axis=1)
print(node_features.shape)
node_features

(6, 9)


array([[1., 0., 1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 0., 0., 0., 0., 0.]])

In [9]:
dihedral_angles = obj.get_dihedral_angles()
dihedral_angles 
# obj.get_edges
# node_features = np.concatenate([face_areas_features,face_sides_features,],axis=1)
edge_features = dihedral_angles

print(edge_features.shape)
edge_features

(12,)


array([1.57079633, 1.57079633, 1.57079633, 1.57079633, 1.57079633,
       1.57079633, 1.57079633, 1.57079633, 1.57079633, 1.57079633,
       1.57079633, 1.57079633])

In [10]:
pos = obj.face_centers
adj_mat = obj.verts_adj_mat
target_variable = obj.get_energy_per_node(pos,adj_mat)

In [11]:
obj.get_pyg_faces_input(x=node_features, edge_attr=edge_features,y=target_variable)

(array([[1., 0., 1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 1., 0., 0., 0., 0., 0., 0.]]),
 array([[0, 1],
        [0, 2],
        [0, 3],
        [0, 4],
        [1, 2],
        [1, 3],
        [1, 5],
        [2, 4],
        [2, 5],
        [3, 4],
        [3, 5],
        [4, 5]]),
 array([1.57079633, 1.57079633, 1.57079633, 1.57079633, 1.57079633,
        1.57079633, 1.57079633, 1.57079633, 1.57079633, 1.57079633,
        1.57079633, 1.57079633]),
 0.7489486695884694,
 array([[ 0. ,  0. , -0.5],
        [ 0. , -0.5,  0. ],
        [ 0.5,  0. ,  0. ],
        [-0.5,  0. ,  0. ],
        [ 0. ,  0.5,  0. ],
        [ 0. ,  0. ,  0.5]]))

# Featurizing loop

In [12]:
face_feature_set_dir = project_dir + os.sep + 'datasets' + os.sep + 'plutonic_polyhedra' + os.sep + 'face_nodes'

if os.path.exists(face_feature_set_dir):
    shutil.rmtree(face_feature_set_dir)
os.makedirs(face_feature_set_dir)

In [13]:
for i, poly_verts in enumerate(poly_list):

    obj = PolyFeaturizer(vertices=poly_verts)

    face_sides_features = encoder.face_sides_bin_encoder(obj.face_sides)
    face_areas_features = obj.face_areas
    node_features = np.concatenate([face_areas_features,face_sides_features,],axis=1)
    
    dihedral_angles = obj.get_dihedral_angles()
    edge_features = dihedral_angles

    pos = obj.face_centers
    adj_mat = obj.faces_adj_mat

    target_variable = obj.get_energy_per_node(pos,adj_mat)

    obj.get_pyg_faces_input(x = node_features, edge_attr=edge_features,y = target_variable)

    filename = face_feature_set_dir + os.sep + str(i) + '.json'
    obj.export_pyg_json(filename)

In [14]:
vert_feature_set_dir = project_dir + os.sep + 'datasets' + os.sep + 'plutonic_polyhedra' + os.sep + 'vert_nodes'

if os.path.exists(vert_feature_set_dir):
    shutil.rmtree(vert_feature_set_dir)
os.makedirs(vert_feature_set_dir)

In [15]:
for i, poly_verts in enumerate(poly_list):

    obj = PolyFeaturizer(vertices=poly_verts)

    node_features = None

    edge_lengths = obj.get_edge_lengths()
    edge_features = edge_lengths

    pos = obj.vertices
    adj_mat = obj.verts_adj_mat

    target_variable = obj.get_energy_per_node(pos,adj_mat)

    obj.get_pyg_faces_input(x = node_features, edge_attr=edge_features,y = target_variable)

    filename = vert_feature_set_dir + os.sep + str(i) + '.json'
    obj.export_pyg_json(filename)

# Testing PolyDataset

In [16]:
from poly_graphs_lib.poly_dataset import PolyhedraDataset

In [17]:
face_dataset = PolyhedraDataset(database_dir = vert_feature_set_dir)
node_dataset = PolyhedraDataset(database_dir = face_feature_set_dir)

In [18]:
face_dataset[0]

Data(x=[4, 1], edge_index=[6, 2], edge_attr=[6], y=2.039644241333008, pos=[4, 3])

In [19]:
node_dataset[0]

Data(x=[4, 9], edge_index=[6, 2], edge_attr=[6], y=0.6798813939094543, pos=[4, 3])